config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 
  get 'musics/idol' => 'musics#idol'
  get 'musics/westernrock' => 'musics#westernrock'
  get 'musics/japaneserock' => 'musics#japaneserock'
  get 'musics/Kpop' => 'musics#Kpop'
  get 'musics/enka' => 'musics#enka'
  get 'musics/hiphop' => 'musics#hiphop'
  get 'musics/japanesepop' => 'musics#japanesepop'
  get 'musics/jazz' => 'musics#jazz'
  get 'musics/anime' => 'musics#anime'
  get 'musics/classic' => 'musics#classic'
  get 'musics/artist_songs/:id' => 'musics#artist_songs', as: :artist_songs
 
  resources :users, only: [:show] # ユーザーマイページへのルーティング
  resources :musics
  resources :songs  do
    resources :likes, only: [:create, :destroy]
  end
  root 'musics#index'
  
end

app/models/song.rb
class Song < ApplicationRecord
    belongs_to :music
    belongs_to :user
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user

    def find_youtube_url
        if youtube_url.present?
          if youtube_url[0..16] == "https://youtu.be/"
            return youtube_url[17..27]
          else
            return youtube_url[32..42]
          end
        else
          # youtube_url が nil の場合の処理を追加
          return "No URL"
        end
    end
    mount_uploader :image, ImageUploader
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
    def new
        @song = Song.new
    end
       
   def create
       @song = Song.new(song_params)
       @song.user_id = current_user.id
       if @song.save
          redirect_to artist_songs_path(@song.music), notice: "曲が投稿されました"
       else
          render :new
       end
   end
   
   def show
    @song = Song.find(params[:id])
    
   end 
   def like
    song = Song.find(params[:id])
    current_user.likes.create(song: song)
    redirect_to song
end

   private
     def song_params
          params.require(:song).permit(:title, :music_id, :youtube_url, :image, :comment)
     end
end

app/helpers/songs_helper.rb
module SongsHelper

end

app/views/songs/new.html.erb
<h1>Song</h1>

<%= form_for @song do |f| %>
  <%= f.label :title, "Title" %>
  <%= f.text_field :title %>

  <%= f.label :music_id, "Artist" %>
  <%= f.collection_select :music_id, Music.all, :id, :content, prompt: "アーティストを選択" %>

  <%= f.submit "Post" %>

  <%= f.label :youtube_url %>
  <%= f.text_field :youtube_url, :size => 140 %>

  <%= f.label :comment, "Comment" %>
  <%= f.text_field :comment %>

  <div class="field">
    <%= f.label :image, "Image" %>
    <%= f.file_field :image %>
  </div>


  
<% end %>

app/views/songs/show.html.erb
<h1>曲詳細</h1>
<ul>

    <li><%= @song.title %></li>
    <iframe width="560" height="315" src="https://www.youtube.com/embed/<%= @song.find_youtube_url %>" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    <%= image_tag @song.image_url, size: "250x200" if @song.image? %>
    <%= @song.comment %>
   
    <% if user_signed_in? %>
    <% if current_user.already_liked?(@song) %>
      <%= button_to song_like_path(@song), method: :delete do %>
        <p>いいねを取り消す</p><%= @song.likes.count %>
      <% end %>
    <% else %>
      <%= button_to song_likes_path(@song), method: :post do %>
        <p>いいね</p><%= @song.likes.count %>
      <% end %>
    <% end %>
  <% else %>
    <p>いいねの数 = </p><%= @song.likes.count %>
  <% end %>


</ul>