config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 
  get 'musics/idol' => 'musics#idol'
  get 'musics/westernrock' => 'musics#westernrock'
  get 'musics/japaneserock' => 'musics#japaneserock'
  get 'musics/Kpop' => 'musics#Kpop'
  get 'musics/enka' => 'musics#enka'
  get 'musics/hiphop' => 'musics#hiphop'
  get 'musics/japanesepop' => 'musics#japanesepop'
  get 'musics/jazz' => 'musics#jazz'
  get 'musics/anime' => 'musics#anime'
  get 'musics/classic' => 'musics#classic'
  get 'musics/artist_songs/:id' => 'musics#artist_songs', as: :artist_songs
 
  resources :users, only: [:show] # ユーザーマイページへのルーティング
  resources :musics
  resources :songs  do
    resources :likes, only: [:create, :destroy]
  end
  root 'musics#index'
  
end

app/models/music.rb
class Music < ApplicationRecord
    has_many :songs
    has_many :songs, dependent: :destroy
    mount_uploader :image, ImageUploader   
    validates :content, uniqueness: true
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create]

    def index
   
    end
 
    def new
        @music = Music.new
    end
    
    def create
        # データベース内に同じ content 値が存在するか確認
      if Music.exists?(content: music_params[:content])
          @music = Music.new
          @music.errors.add(:content, "アーティスト名はすでに存在します")
          render :new
      else
          @music = Music.new(music_params)
          if @music.save
            # カテゴリーに応じてリダイレクト先を設定
            if @music.category == "idol"
              redirect_to musics_idol_path
            elsif @music.category == "japaneserock"
              redirect_to musics_japaneserock_path
            elsif @music.category == "japanesepop"
              redirect_to musics_japanesepop_path
             elsif @music.category == "jazz"
              redirect_to musics_jazz_path 
            elsif @music.category == "hiphop"
              redirect_to musics_hiphop_path 
            elsif @music.category == "enka"
              redirect_to musics_enka_path 
            elsif @music.category == "anime"
              redirect_to musics_anime_path 
            elsif @music.category == "classic"
              redirect_to musics_classic_path 
            elsif @music.category == "Kpop"
              redirect_to musics_Kpop_path
            else
              # その他のカテゴリーに対するリダイレクト先を設定する場合、ここに追加
              redirect_to musics_westernrock_path
            end
          else
             render :new
          end
      end
    end
    
    def idol
      if params[:search] == nil
        @musics = Music.all
      elsif params[:search] == ''
        @musics = Music.all
      else
        @musics = Music.where("content LIKE ? ",'%' + params[:search] + '%')
      end
    end 
      
  def westernrock
    if params[:search] == nil
      @musics = Music.all
    elsif params[:search] == ''
      @musics = Music.all
    else
      @musics = Music.where("content LIKE ? ",'%' + params[:search] + '%')
    end
  end
     
  def japaneserock
    if params[:search] == nil
      @musics = Music.all
    elsif params[:search] == ''
      @musics = Music.all
    else
      @musics = Music.where("content LIKE ? ",'%' + params[:search] + '%')
    end
  end

  def japanesepop
    if params[:search] == nil
      @musics = Music.all
    elsif params[:search] == ''
      @musics = Music.all
    else
      @musics = Music.where("content LIKE ? ",'%' + params[:search] + '%')
    end
  end

  def enka
    if params[:search] == nil
      @musics = Music.all
    elsif params[:search] == ''
      @musics = Music.all
    else
      @musics = Music.where("content LIKE ? ",'%' + params[:search] + '%')
    end
  end

  def jazz
    if params[:search] == nil
      @musics = Music.all
    elsif params[:search] == ''
      @musics = Music.all
    else
      @musics = Music.where("content LIKE ? ",'%' + params[:search] + '%')
    end
  end

  def hiphop
    if params[:search] == nil
      @musics = Music.all
    elsif params[:search] == ''
      @musics = Music.all
    else
      @musics = Music.where("content LIKE ? ",'%' + params[:search] + '%')
    end
  end

  def Kpop
    if params[:search] == nil
      @musics = Music.all
    elsif params[:search] == ''
      @musics = Music.all
    else
      @musics = Music.where("content LIKE ? ",'%' + params[:search] + '%')
    end
  end

  def classic
    if params[:search] == nil
      @musics = Music.all
    elsif params[:search] == ''
      @musics = Music.all
    else
      @musics = Music.where("content LIKE ? ",'%' + params[:search] + '%')
    end
  end

  def anime
    if params[:search] == nil
      @musics = Music.all
    elsif params[:search] == ''
      @musics = Music.all
    else
      @musics = Music.where("content LIKE ? ",'%' + params[:search] + '%')
    end
  end

  def destroy
    music = Music.find(params[:id])
    category = music.category 
  
    music.destroy
  
    case category
    when "idol"
      redirect_to musics_idol_path
    when "japaneserock"
      redirect_to musics_japaneserock_path
    when "anime"
      redirect_to musics_anime_path
    when "Kpop"
      redirect_to musics_Kpop_path
    when "enka"
      redirect_to musics_enka_path
    when "japanesepop"
      redirect_to musics_japanesepop_path
    when "jazz"
      redirect_to musics_jazz_path
    when "hiphop"
      redirect_to musics_hiphop_path
    when "classic"
      redirect_to musics_classic_path
    else
      redirect_to musics_westernrock_path
    end
  end


  def artist_songs
    @music = Music.find(params[:id])
    @new_song = Song.new
    @songs = @music.songs
  end

      private
      def music_params
        params.require(:music).permit(:music, :hand, :note, :content, :category, :image)
      end
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/views/musics/Kpop.html.erb
<h1>K-POP</h1>
<% if user_signed_in? %>
  <%= link_to "マイページへ", user_path(current_user.id) %>
<% end %>
<h3>投稿を検索</h3>
 <%= form_tag({controller:"musics",action:"Kpop"}, method: :get) do %>
   <%= text_field_tag :search %>
   <%= submit_tag '検索する'  %>
<% end %>
<% @musics.each do |t| %>
  <% if t.category == "Kpop" %>  
  <%= image_tag t.image_url, size: "250x200" if t.image? %>
    <p>アーティスト名:<%= t.content %></p>
     <%= button_to "削除する", music_path(t.id), method: :delete %>
     <%= link_to "曲名一覧ページへ", artist_songs_path(id: t.id) %>

  <% end %>
<% end %>

app/views/musics/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
       <h2>すでに存在するデータです</h2>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/musics/anime.html.erb
<h1>アニソン</h1>
<% if user_signed_in? %>
  <%= link_to "マイページへ", user_path(current_user.id) %>
<% end %>
<h3>投稿を検索</h3>
 <%= form_tag({controller:"musics",action:"anime"}, method: :get) do %>
   <%= text_field_tag :search %>
   <%= submit_tag '検索する'  %>
<% end %>
<% @musics.each do |t| %>
  <% if t.category == "anime" %>  
  <%= image_tag t.image_url, size: "250x200" if t.image? %>
    <p>アーティスト名:<%= t.content %></p>
     <%= button_to "削除する", music_path(t.id), method: :delete %>
     <%= link_to "曲名一覧ページへ", artist_songs_path(id: t.id) %>

  <% end %>
<% end %>

app/views/musics/artist_songs.html.erb
<h1><%= @music.content %>曲一覧</h1>

<ul>
  <% @songs.each do |t| %>
    <li><%= t.title %></li>
    <iframe width="560" height="315" src="https://www.youtube.com/embed/<%= t.find_youtube_url %>" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    <%= link_to "詳細へ", song_path(t.id) %>
    <% end %>
</ul>

app/views/musics/classic.html.erb
<h1>クラシック</h1>
<% if user_signed_in? %>
  <%= link_to "マイページへ", user_path(current_user.id) %>
<% end %>
<h3>投稿を検索</h3>
 <%= form_tag({controller:"musics",action:"classic"}, method: :get) do %>
   <%= text_field_tag :search %>
   <%= submit_tag '検索する'  %>
<% end %>
<% @musics.each do |t| %>
  <% if t.category == "classic" %>  
  <%= image_tag t.image_url, size: "250x200" if t.image? %>
    <p>アーティスト名:<%= t.content %></p>
     <%= button_to "削除する", music_path(t.id), method: :delete %>
     <%= link_to "曲名一覧ページへ", artist_songs_path(id: t.id) %>

  <% end %>
<% end %>

app/views/musics/enka.html.erb
<h1>演歌</h1>
<% if user_signed_in? %>
  <%= link_to "マイページへ", user_path(current_user.id) %>
<% end %>
<h3>投稿を検索</h3>
 <%= form_tag({controller:"musics",action:"enka"}, method: :get) do %>
   <%= text_field_tag :search %>
   <%= submit_tag '検索する'  %>
<% end %>
<% @musics.each do |t| %>
  <% if t.category == "enka" %>  
  <%= image_tag t.image_url, size: "250x200" if t.image? %>
    <p>アーティスト名:<%= t.content %></p>
     <%= button_to "削除する", music_path(t.id), method: :delete %>
     <%= link_to "曲名一覧ページへ", artist_songs_path(id: t.id) %>

  <% end %>
<% end %>

app/views/musics/hiphop.html.erb
<h1>ヒップホップ</h1>
<% if user_signed_in? %>
  <%= link_to "マイページへ", user_path(current_user.id) %>
<% end %>
<h3>投稿を検索</h3>
 <%= form_tag({controller:"musics",action:"hiphop"}, method: :get) do %>
   <%= text_field_tag :search %>
   <%= submit_tag '検索する'  %>
<% end %>
<% @musics.each do |t| %>
  <% if t.category == "hiphop" %>  
  <%= image_tag t.image_url, size: "250x200" if t.image? %>
    <p>アーティスト名:<%= t.content %></p>
     <%= button_to "削除する", music_path(t.id), method: :delete %>
     <%= link_to "曲名一覧ページへ", artist_songs_path(id: t.id) %>

  <% end %>
<% end %>

app/views/musics/idol.html.erb
<h1>アイドル</h1>
<% if user_signed_in? %>
  <%= link_to "マイページへ", user_path(current_user.id) %>
<% end %>
<h3>投稿を検索</h3>
 <%= form_tag({controller:"musics",action:"idol"}, method: :get) do %>
   <%= text_field_tag :search %>
   <%= submit_tag '検索する'  %>
<% end %>
<% @musics.each do |t| %>
  <% if t.category == "idol" %>  
    <%= image_tag t.image_url, size: "250x200" if t.image? %>
    <p>アーティスト名:<%= t.content %></p>
    <%= link_to "曲名一覧ページへ", artist_songs_path(id: t.id) %>
     <%= button_to "削除する", music_path(t.id), method: :delete %>
  <% end %>

  
<% end %>

app/views/musics/japanesepop.html.erb
<h1>J-POP</h1>
<% if user_signed_in? %>
  <%= link_to "マイページへ", user_path(current_user.id) %>
<% end %>
<h3>投稿を検索</h3>
 <%= form_tag({controller:"musics",action:"japanesepop"}, method: :get) do %>
   <%= text_field_tag :search %>
   <%= submit_tag '検索する'  %>
<% end %>
<% @musics.each do |t| %>
  <% if t.category == "japanesepop" %>  
  <%= image_tag t.image_url, size: "250x200" if t.image? %>
    <p>アーティスト名:<%= t.content %></p>
     <%= button_to "削除する", music_path(t.id), method: :delete %>
     <%= link_to "曲名一覧ページへ", artist_songs_path(id: t.id) %>

  <% end %>
<% end %>

app/views/musics/japaneserock.html.erb
<h1>邦ロック</h1>
<% if user_signed_in? %>
  <%= link_to "マイページへ", user_path(current_user.id) %>
<% end %>
<h3>投稿を検索</h3>
 <%= form_tag({controller:"musics",action:"japaneserock"}, method: :get) do %>
   <%= text_field_tag :search %>
   <%= submit_tag '検索する'  %>
<% end %>
<% @musics.each do |t| %>
  <% if t.category == "japaneserock" %>  
  <%= image_tag t.image_url, size: "250x200" if t.image? %>
    <p>アーティスト名:<%= t.content %></p>
     <%= button_to "削除する", music_path(t.id), method: :delete %>
     <%= link_to "曲名一覧ページへ", artist_songs_path(id: t.id) %>

  <% end %>
<% end %>

app/views/musics/jazz.html.erb
<h1>ジャズ</h1>
<% if user_signed_in? %>
  <%= link_to "マイページへ", user_path(current_user.id) %>
<% end %>
<h3>投稿を検索</h3>
 <%= form_tag({controller:"musics",action:"jazz"}, method: :get) do %>
   <%= text_field_tag :search %>
   <%= submit_tag '検索する'  %>
<% end %>
<% @musics.each do |t| %>
  <% if t.category == "jazz" %>  
  <%= image_tag t.image_url, size: "250x200" if t.image? %>
    <p>アーティスト名:<%= t.content %></p>
     <%= button_to "削除する", music_path(t.id), method: :delete %>
     <%= link_to "曲名一覧ページへ", artist_songs_path(id: t.id) %>

  <% end %>
<% end %>

app/views/musics/new.html.erb
<h1>Artist</h1>

<%= form_for @music do |f| %>
  <%= render 'musics/error_messages', model: f.object %> 
  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <%= f.label :content,"アーティスト名" %>
  <%= f.text_field :content %>

  <%= f.select :category, [["邦ロック", "japaneserock"],["洋ロック", "westernrock"], ["J-POP", "japanesepop"], ["K-POP", "Kpop"], ["アイドル", "idol"], ["アニメ", "anime"], ["ヒップホップ", "hiphop"],["ジャズ", "jazz"], ["クラシック", "classic"], ["演歌", "enka"]], include_blank: "ジャンル" %>


  <%= f.submit "投稿する" %>
<% end %>

<%= link_to "一覧に戻る", musics_path %>

app/views/musics/westernrock.html.erb
<h1>洋楽</h1>
<% if user_signed_in? %>
  <%= link_to "マイページへ", user_path(current_user.id) %>
<% end %>
<h3>投稿を検索</h3>
 <%= form_tag({controller:"musics",action:"westernrock"}, method: :get) do %>
   <%= text_field_tag :search %>
   <%= submit_tag '検索する'  %>
<% end %>
<% @musics.each do |t| %>
  <% if t.category == "westernrock" %>  
  <%= image_tag t.image_url, size: "250x200" if t.image? %>
    <p>アーティスト名:<%= t.content %></p>
     <%= button_to "削除する", music_path(t.id), method: :delete %>
     <%= link_to "曲名一覧ページへ", artist_songs_path(id: t.id) %>

  <% end %>
<% end %>